export const MatchState = {
    QUEUED_FOR_DOWNLOADING: 'QUEUED FOR DOWNLOADING',
    QUEUED_FOR_PROCESSING: 'QUEUED FOR PROCESSING',
    DOWNLOADING: 'DOWNLOADING',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED'
};